name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'deploy/helm/**'
      - 'src/VERSION'
  workflow_dispatch:

env:
  workflow_file_name: dispatch_workflow_deploy.yaml
  owner: cloudforet-io
  repo: cloudforet
  ref: master
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  sync_and_trigger:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          inputs: '{"repository" : "${{ github.repository }}"}'
          trigger_workflow: true
          wait_workflow: true
      - name: Job Failure Notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,workflow,eventName,job
          author_name: Github Action Slack

  sync_only:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ${{ env.owner }}
          repo: ${{ env.repo }}
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: ${{ env.workflow_file_name }}
          ref: ${{ env.ref }}
          wait_interval: 10
          inputs: '{"repository" : "${{ github.repository }}" , "sync_only" : "true"}'
          trigger_workflow: true
          wait_workflow: true
      - name: Job Failure Notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,workflow,eventName,job
          author_name: Github Action Slack
