name: "[Dispatch] Init repository"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'target repository'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'init'
    steps:
      - uses: actions/checkout@v2
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r actions/requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: init deploy
        run: |
          python actions/src/main.py --repo ${{ github.event.inputs.repo }} --init
